import {
  type Course,
  type CourseOffer,
  type CurrencyCode,
  type Duration,
  type LocalizedString,
  type MarketId,
  courseSchema,
} from "@/lib/content/schema";

const l = (es: string, en: string): LocalizedString => ({ es, en });

const days = (count: number, es: string, en: string): Duration => ({
  days: count,
  label: l(es, en),
});

const price = (amount: number, currency: CurrencyCode) => ({ amount, currency });

const offer = (
  marketId: MarketId,
  modality: CourseOffer["modality"],
  currency: CurrencyCode,
  withKit?: number,
  withoutKit?: number,
): CourseOffer => ({
  marketId,
  modality,
  ...(withKit ? { withKit: price(withKit, currency) } : {}),
  ...(withoutKit ? { withoutKit: price(withoutKit, currency) } : {}),
});

const commonBusinessModules = [
  l("Fotografía profesional y redes sociales", "Professional photography and social media"),
  l("Marketing, publicidad y ventas", "Marketing, advertising and sales"),
  l("Proveedores", "Suppliers"),
  l("Cómo conseguir las primeras clientas", "How to attract your first clients"),
  l("Cómo proyectarse profesionalmente", "How to position yourself professionally"),
];

const commonMentoringIncludes = [
  l("Acompañamiento por un año", "One year of support"),
  l("Acceso a grupo VIP de WhatsApp", "Access to a VIP WhatsApp group"),
  l("Evaluación de trabajos realizados", "Review of completed work"),
  l("Resolución de dudas durante procedimientos", "Support with questions during procedures"),
  l("Orientación para convertirlo en negocio", "Guidance to turn the skill into a business"),
];

export const courses = courseSchema.array().parse([
  {
    id: "curso-micropigmentacion-cejas",
    imageId: "curso-cejas-pigmentos",
    kind: "professional",
    slug: l("curso-micropigmentacion-cejas", "brow-micropigmentation-course"),
    name: l(
      "Curso profesional de micropigmentación de cejas",
      "Professional brow micropigmentation course",
    ),
    summary: l(
      "Formación profesional en efecto polvo y efecto maquillaje, con teoría, práctica y modelo real.",
      "Professional training in powder brows and makeup-effect brows, with theory, practice and a real model.",
    ),
    duration: days(3, "3 días", "3 days"),
    certification: l("Doble certificado", "Double certificate"),
    modalities: ["virtual", "presencial", "personalizada"],
    modules: [
      l("Fundamentos de la micropigmentación", "Micropigmentation fundamentals"),
      l("Bioseguridad y ética profesional", "Biosafety and professional ethics"),
      l("Tipos de piel y cicatrización", "Skin types and healing"),
      l("Colorimetría aplicada a cejas", "Brow colorimetry"),
      l("Visagismo bajo medidas faciales", "Brow mapping using facial measurements"),
      l("Técnicas: efecto polvo y efecto maquillaje", "Techniques: powder brows and makeup-effect brows"),
      l("Uso de dermógrafo y agujas", "Dermograph and needle use"),
      l("Procedimiento paso a paso", "Step-by-step procedure"),
      l("Cuidados postratamiento", "Aftercare"),
      l("Práctica con modelo real", "Practice with a real model"),
      ...commonBusinessModules,
    ],
    includes: [
      l("Kit profesional", "Professional kit"),
      l("Dermógrafo profesional y dos tintas", "Professional dermograph and two pigments"),
      l("Pie de rey, lápiz de diseño, hilo y pincel", "Caliper, design pencil, thread and brush"),
      l("Piel de práctica, anillos y agujas", "Practice skin, rings and needles"),
      l("Obsequio: elegir lifting, laminado o henna", "Gift: choose lash lift, lamination or henna"),
      ...commonMentoringIncludes,
    ],
    offers: [
      offer("colombia", "virtual", "COP", 2200000, 1600000),
      offer("colombia", "presencial", "COP", 3200000, 2600000),
      offer("colombia", "personalizada", "COP", 4000000, 3500000),
      offer("espana-europa", "virtual", "EUR", 800, 500),
      offer("espana-europa", "presencial", "EUR", 1000, 700),
      offer("espana-europa", "personalizada", "EUR", 1300, 1000),
    ],
    downloadId: "curso-micropigmentacion-cejas",
  },
  {
    id: "curso-micropigmentacion-labios",
    imageId: "curso-labios-demostracion",
    kind: "professional",
    slug: l("curso-micropigmentacion-labios", "lip-micropigmentation-course"),
    name: l(
      "Curso profesional de micropigmentación y neutralización labial",
      "Professional lip micropigmentation and neutralization course",
    ),
    summary: l(
      "Formación en full lips, acuarela y neutralización labial, con teoría, práctica y modelo real.",
      "Training in full lips, watercolor lips and lip neutralization, with theory, practice and a real model.",
    ),
    duration: days(3, "3 días", "3 days"),
    certification: l("Doble certificado", "Double certificate"),
    modalities: ["virtual", "presencial", "personalizada"],
    modules: [
      l("Fundamentos de micropigmentación y neutralización", "Micropigmentation and neutralization fundamentals"),
      l("Bioseguridad y ética profesional", "Biosafety and professional ethics"),
      l("Tipos de piel y cicatrización", "Skin types and healing"),
      l("Colorimetría aplicada en labios", "Lip colorimetry"),
      l("Visagismo bajo medidas", "Lip mapping and measurements"),
      l("Técnicas: full lips, acuarela y neutralización", "Techniques: full lips, watercolor lips and neutralization"),
      l("Uso de dermógrafo y agujas", "Dermograph and needle use"),
      l("Procedimiento paso a paso", "Step-by-step procedure"),
      l("Cuidados postratamiento", "Aftercare"),
      l("Práctica con modelo real", "Practice with a real model"),
      ...commonBusinessModules,
    ],
    includes: [
      l("Kit profesional", "Professional kit"),
      l("Dermógrafo profesional y dos tintas", "Professional dermograph and two pigments"),
      l("Pie de rey, lápiz de diseño, hilo y pincel", "Caliper, design pencil, thread and brush"),
      l("Piel de práctica, anillos y agujas", "Practice skin, rings and needles"),
      l("Obsequio: elegir lifting, laminado o henna", "Gift: choose lash lift, lamination or henna"),
      ...commonMentoringIncludes,
    ],
    offers: [
      offer("colombia", "virtual", "COP", 2500000, 1900000),
      offer("colombia", "presencial", "COP", 3500000, 2900000),
      offer("colombia", "personalizada", "COP", 4200000, 3600000),
      offer("espana-europa", "virtual", "EUR", 800, 500),
      offer("espana-europa", "presencial", "EUR", 1000, 700),
      offer("espana-europa", "personalizada", "EUR", 1300, 1000),
    ],
    downloadId: "curso-micropigmentacion-labios",
  },
  {
    id: "masterclass-laminado-cejas",
    imageId: "curso-laminado-cejas",
    kind: "masterclass",
    slug: l("masterclass-laminado-cejas", "brow-lamination-masterclass"),
    name: l("Master Class Laminado de Cejas", "Brow Lamination Master Class"),
    summary: l(
      "Masterclass de un día sobre laminado, visagismo, cuidados, materiales y marketing.",
      "One-day masterclass on lamination, brow mapping, aftercare, materials and marketing.",
    ),
    duration: days(1, "1 día", "1 day"),
    certification: l("Certificado", "Certificate"),
    modalities: ["virtual", "presencial"],
    modules: [
      l("Qué es el laminado", "What brow lamination is"),
      l("A quién se recomienda y a quién no", "Who it is and is not recommended for"),
      l("Paso a paso", "Step by step"),
      l("Medidas faciales y visagismo", "Facial measurements and brow mapping"),
      l("Cuidados", "Aftercare"),
      l("Materiales", "Materials"),
      ...commonBusinessModules,
    ],
    includes: [
      l("Kit profesional", "Professional kit"),
      l("Henna, perfiladores, pie de rey y lápiz de diseño", "Henna products, profilers, caliper and design pencil"),
      l("Kit de laminado completo", "Complete lamination kit"),
      ...commonMentoringIncludes,
    ],
    offers: [
      offer("colombia", "virtual", "COP", 350000, 270000),
      offer("colombia", "presencial", "COP", 450000, 370000),
      offer("espana-europa", "virtual", "EUR", 300),
      offer("espana-europa", "presencial", "EUR", 400),
    ],
    downloadId: "masterclass-laminado-cejas",
  },
  {
    id: "masterclass-lifting-pestanas",
    imageId: "curso-lifting-pestanas",
    kind: "masterclass",
    slug: l("masterclass-lifting-pestanas", "lash-lift-masterclass"),
    name: l("Master Class Lifting de Pestañas", "Lash Lift Master Class"),
    summary: l(
      "Masterclass de un día sobre lifting, cuidados, materiales, proveedores y marketing.",
      "One-day masterclass on lash lift, aftercare, materials, suppliers and marketing.",
    ),
    duration: days(1, "1 día", "1 day"),
    certification: l("Certificado", "Certificate"),
    modalities: ["virtual", "presencial"],
    modules: [
      l("Qué es el lifting", "What lash lifting is"),
      l("A quién se recomienda y a quién no", "Who it is and is not recommended for"),
      l("Paso a paso", "Step by step"),
      l("Cuidados", "Aftercare"),
      l("Materiales", "Materials"),
      ...commonBusinessModules,
    ],
    includes: [
      l("Kit profesional", "Professional kit"),
      l("Moldes, peine, aplicadores y parches", "Molds, comb, applicators and pads"),
      l("Kit de lifting completo", "Complete lash lift kit"),
      ...commonMentoringIncludes,
    ],
    offers: [
      offer("colombia", "virtual", "COP", 350000, 270000),
      offer("colombia", "presencial", "COP", 450000, 370000),
      offer("espana-europa", "virtual", "EUR", 300),
      offer("espana-europa", "presencial", "EUR", 400),
    ],
    downloadId: "masterclass-lifting-pestanas",
  },
  {
    id: "masterclass-cejas-henna",
    imageId: "curso-cejas-henna",
    kind: "masterclass",
    slug: l("masterclass-cejas-henna", "henna-brows-masterclass"),
    name: l("Master Class Cejas en Henna", "Henna Brows Master Class"),
    summary: l(
      "Masterclass de un día sobre henna, visagismo, cuidados, materiales y marketing.",
      "One-day masterclass on henna brows, mapping, aftercare, materials and marketing.",
    ),
    duration: days(1, "1 día", "1 day"),
    certification: l("Certificado", "Certificate"),
    modalities: ["virtual", "presencial"],
    modules: [
      l("Qué es la henna", "What henna brows are"),
      l("A quién se recomienda y a quién no", "Who it is and is not recommended for"),
      l("Paso a paso", "Step by step"),
      l("Medidas faciales y visagismo", "Facial measurements and brow mapping"),
      l("Cuidados", "Aftercare"),
      l("Materiales", "Materials"),
      ...commonBusinessModules,
    ],
    includes: [
      l("Kit profesional", "Professional kit"),
      l("Henna, perfiladores, pie de rey y lápiz de diseño", "Henna products, profilers, caliper and design pencil"),
      l("Cepillos, perfiladores, cuchillas y estuche", "Brushes, profilers, razors and case"),
      ...commonMentoringIncludes,
    ],
    offers: [
      offer("colombia", "virtual", "COP", 180000),
      offer("colombia", "presencial", "COP", 280000),
      offer("espana-europa", "virtual", "EUR", 180),
      offer("espana-europa", "presencial", "EUR", 280),
    ],
    downloadId: "masterclass-cejas-henna",
  },
] satisfies Course[]);
